// Catálogo geográfico oficial Edomex ↔ CDMX

export const ESTADOS = [
  { id: 'edomex', label: 'Estado de México' },
  { id: 'cdmx', label: 'Ciudad de México' },
];

// 125 municipios oficiales del Estado de México
export const MUNICIPIOS_EDOMEX = [
  'Acambay de Ruíz Castañeda',
  'Acolman',
  'Aculco',
  'Almoloya de Alquisiras',
  'Almoloya de Juárez',
  'Almoloya del Río',
  'Amanalco',
  'Amatepec',
  'Amecameca',
  'Apaxco',
  'Atenco',
  'Atizapán',
  'Atizapán de Zaragoza',
  'Atlacomulco',
  'Atlautla',
  'Axapusco',
  'Ayapango',
  'Calimaya',
  'Capulhuac',
  'Coacalco de Berriozábal',
  'Coatepec Harinas',
  'Cocotitlán',
  'Coyotepec',
  'Cuautitlán',
  'Cuautitlán Izcalli',
  'Chalco',
  'Chapa de Mota',
  'Chapultepec',
  'Chiautla',
  'Chicoloapan',
  'Chiconcuac',
  'Chimalhuacán',
  'Donato Guerra',
  'Ecatepec de Morelos',
  'Ecatzingo',
  'Huehuetoca',
  'Hueypoxtla',
  'Huixquilucan',
  'Isidro Fabela',
  'Ixtapaluca',
  'Ixtapan de la Sal',
  'Ixtapan del Oro',
  'Ixtlahuaca',
  'Xalatlaco',
  'Jaltenco',
  'Jilotepec',
  'Jilotzingo',
  'Jiquipilco',
  'Jocotitlán',
  'Joquicingo',
  'Juchitepec',
  'Lerma',
  'Luvianos',
  'Malinalco',
  'Melchor Ocampo',
  'Metepec',
  'Mexicaltzingo',
  'Morelos',
  'Naucalpan de Juárez',
  'Nezahualcóyotl',
  'Nextlalpan',
  'Nicolás Romero',
  'Nopaltepec',
  'Ocoyoacac',
  'Ocuilan',
  'El Oro',
  'Otumba',
  'Otzoloapan',
  'Otzolotepec',
  'Ozumba',
  'Papalotla',
  'La Paz',
  'Polotitlán',
  'Rayón',
  'San Antonio la Isla',
  'San Felipe del Progreso',
  'San José del Rincón',
  'San Martín de las Pirámides',
  'San Mateo Atenco',
  'San Simón de Guerrero',
  'Santo Tomás',
  'Soyaniquilpan de Juárez',
  'Sultepec',
  'Tecámac',
  'Tejupilco',
  'Temamatla',
  'Temascalapa',
  'Temascalcingo',
  'Temascaltepec',
  'Temoaya',
  'Tenancingo',
  'Tenango del Aire',
  'Tenango del Valle',
  'Teoloyucan',
  'Teotihuacán',
  'Tepetlaoxtoc',
  'Tepetlixpa',
  'Tepotzotlán',
  'Tequixquiac',
  'Texcaltitlán',
  'Texcalyacac',
  'Texcoco',
  'Tezoyuca',
  'Tianguistenco',
  'Timilpan',
  'Tlalmanalco',
  'Tlalnepantla de Baz',
  'Tlatlaya',
  'Toluca',
  'Tonanitla',
  'Tonatico',
  'Tultepec',
  'Tultitlán',
  'Valle de Bravo',
  'Valle de Chalco Solidaridad',
  'Villa de Allende',
  'Villa del Carbón',
  'Villa Guerrero',
  'Villa Victoria',
  'Xonacatlán',
  'Zacazonapan',
  'Zacualpan',
  'Zinacantepec',
  'Zumpahuacán',
  'Zumpango',
];

// Verificación: MUNICIPIOS_EDOMEX.length debe ser 125
// console.assert(MUNICIPIOS_EDOMEX.length === 125, `EdoMex tiene ${MUNICIPIOS_EDOMEX.length} municipios, se esperaban 125`);

// 16 alcaldías oficiales de la Ciudad de México
export const ALCALDIAS_CDMX = [
  'Álvaro Obregón',
  'Azcapotzalco',
  'Benito Juárez',
  'Coyoacán',
  'Cuajimalpa de Morelos',
  'Cuauhtémoc',
  'Gustavo A. Madero',
  'Iztacalco',
  'Iztapalapa',
  'La Magdalena Contreras',
  'Miguel Hidalgo',
  'Milpa Alta',
  'Tláhuac',
  'Tlalpan',
  'Venustiano Carranza',
  'Xochimilco',
];

// Puntos de referencia conocidos por municipio/alcaldía (opcional, para sugerencias)
export const PUNTOS_REFERENCIA = {
  edomex: {
    'Atizapán de Zaragoza': ['Plaza Satélite', 'Metro Cuatro Caminos', 'Hospital General de Atizapán'],
    'Coacalco de Berriozábal': ['Plaza Las Américas Coacalco', 'Hospital General de Coacalco'],
    'Cuautitlán Izcalli': ['Hospital Regional HRDZ', 'Parque Industrial Izcalli', 'Plaza Cuautitlán Izcalli'],
    'Ecatepec de Morelos': ['Metro Ciudad Azteca', 'Metro Ecatepec', 'Hospital General de Ecatepec', 'Plaza Las Américas Ecatepec'],
    'Naucalpan de Juárez': ['Parque Industrial Naucalpan', 'Plaza Satélite (acceso Naucalpan)', 'Hospital Ángeles Naucalpan'],
    'Nezahualcóyotl': ['Metro Pantitlán (Neza)', 'Hospital General de Nezahualcóyotl'],
    'Tlalnepantla de Baz': ['Metro El Rosario', 'Parque Industrial Tlalnepantla', 'Hospital General de Tlalnepantla'],
    'Toluca': ['Terminal de Autobuses Toluca', 'IMSS Toluca', 'Plaza Sendero Toluca', 'Aeropuerto Internacional de Toluca'],
    'Tecámac': ['Metro Ojo de Agua', 'Plaza Galerías Tecámac'],
    'Ixtapaluca': ['Plaza Ixtapaluca', 'IMSS Ixtapaluca'],
    'Chimalhuacán': ['Palacio Municipal de Chimalhuacán', 'Metro Pantitlán (Chimalhuacán)'],
    'Metepec': ['Plaza Outlet Lerma', 'Hospital Materno Perinatal Metepec'],
    'Chalco': ['Central de Autobuses Chalco', 'Hospital General de Chalco'],
    'Tultitlán': ['Parque Industrial Tultitlán', 'Palacio Municipal de Tultitlán'],
    'Nicolás Romero': ['Plaza Nicolás Romero', 'Hospital General Nicolás Romero'],
    'Zumpango': ['Terminal de Autobuses Zumpango', 'Metro Ojo de Agua (zona Zumpango)'],
    'Huixquilucan': ['Interlomas (Plaza)', 'Perisur Huixquilucan'],
  },
  cdmx: {
    'Cuauhtémoc': ['Metro Balderas', 'Metro Hidalgo', 'Metro Bellas Artes', 'Hospital General de México', 'Eje Central / Bucareli'],
    'Benito Juárez': ['Metro Insurgentes', 'Metro Etiopía', 'WTC Ciudad de México'],
    'Gustavo A. Madero': ['Metro Indios Verdes', 'Metro La Raza', 'Terminal Norte (Central del Norte)', 'Hospital General Ticomán'],
    'Azcapotzalco': ['Metro El Rosario', 'Metro Ferrería', 'Parque Industrial Vallejo'],
    'Iztapalapa': ['Metro Pantitlán', 'Central de Autobuses de Oriente (TAPO)', 'Hospital General de Iztapalapa'],
    'Miguel Hidalgo': ['Metro Tacubaya', 'Metro Observatorio', 'Santa Fe (Torres Pedregal)'],
    'Álvaro Obregón': ['Metro Barranca del Muerto', 'Metro Mixcoac', 'Terminal Poniente (Observatorio)'],
    'Venustiano Carranza': ['Aeropuerto Internacional AICM', 'Metro Terminal Aérea', 'TAPO'],
    'Coyoacán': ['Metro Copilco', 'Metro Universidad', 'UNAM Ciudad Universitaria'],
    'Tlalpan': ['Metro Estadio Azteca', 'IMSS Sur (Villa Coapa)', 'Periférico Sur / Perisur'],
    'Iztacalco': ['Metro Apatlaco', 'Metro Velódromo'],
    'Xochimilco': ['Tren Ligero Xochimilco', 'Hospital General Xochimilco'],
    'Cuajimalpa de Morelos': ['Santa Fe (Cuajimalpa)', 'Hospital Ángeles Santa Fe'],
    'Tláhuac': ['Metro Tláhuac (Línea 12)', 'Hospital General Tláhuac'],
    'La Magdalena Contreras': ['Periférico Sur / La Magdalena', 'Mercado de La Magdalena'],
    'Milpa Alta': ['Palacio Municipal Milpa Alta'],
  },
};

export function getPuntosReferencia(estado, municipioOAlcaldia) {
  if (!estado || !municipioOAlcaldia) return [];
  return PUNTOS_REFERENCIA[estado]?.[municipioOAlcaldia] || [];
}

export function getMunicipiosOAlcaldias(estado) {
  if (estado === 'edomex') return MUNICIPIOS_EDOMEX;
  if (estado === 'cdmx') return ALCALDIAS_CDMX;
  return [];
}

export function getTotalMunicipiosEdomex() {
  return MUNICIPIOS_EDOMEX.length; // debe ser 125
}